### ISSUE TITLE
Problem with Trac 1.0.1

### ISSUE THREAD

**Issue by kleh** [chevah/trac-bootstrap-theme#2]
Hi!

I installed newest Trac v 1.0.1 and tried to use this theme for it. I know that readme file says that it is guaranteed to work with version 0.12. It seems to work fine, but there is one irritating problem, left side nav-panel text (links) flows over the wiki container.
Check the attached image for the problem. Do you know any solution for this problem?
![Kuvankaappaus 2013-3-15 kello 19 55 15](https://f.cloud.github.com/assets/3701987/265433/85212328-8db0-11e2-818d-038427af9ef5.png)
- kleh -

**Comment by ottok** [comment]
The reason seems to be patch.css and trac.css which both contain the rule
  .nav li { white-space: nowrap; }

At least for the sidebar, we should have "white-space: normal;". Perhaps the solution would be something like 
 .sidebar-nav .nav li { white-space: normal; }

**Comment by kleh** [comment]
Yes, problem is really in  trac.css, which is provided by Trac and in patch.css. I changed white-space to normal and it fixed the problem.
